alphagov/verify-matching-service-adapter

- startup.sh
> BAU: Fix startup.sh to work with latest version of verify-local-startup

- verify-matching-service-test-tool/src/main/java/uk/gov/ida/verifymatchingservicetesttool/scenarios/LevelOfAssuranceOneScenario.java
- verify-matching-service-test-tool/src/main/java/uk/gov/ida/verifymatchingservicetesttool/scenarios/LevelOfAssuranceTwoScenario.java
- verify-matching-service-test-tool/src/main/java/uk/gov/ida/verifymatchingservicetesttool/scenarios/OptionalAddressFieldsExcludedScenario.java
- verify-matching-service-test-tool/src/main/java/uk/gov/ida/verifymatchingservicetesttool/scenarios/UserAccountCreationScenario.java
- verify-matching-service-test-tool/src/main/java/uk/gov/ida/verifymatchingservicetesttool/utils/FileUtils.java
We weren't closing the examples files after reading them, which seems to
have been causing the occasional weird thing to happen now we're
calling `System.exit()`.
I'm using a try-with-resources statement to close the Closeable classes
in FileUtils: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
Authors: @richardtowers
> bau: Test tool - close file resources after use

- verify-matching-service-test-tool/build.gradle
There was an issue with the way we'd set up our copy tasks where they
would run immediately, instead of as part of the task. This is due to
the confusing `doLast` stuff in the gradle DSL wherein code in the block
executes as soon as the gradle file is interpreted unless it's in some
special kind of task or a doLast block.
See https://docs.gradle.org/current/userguide/tutorial_using_tasks.html
When one ran gradle clean test the following was happening:
* As soon as the file was parsed, the `copy` command was running and
copying the files into build.
* When the clean task ran it would remove the build directory.
* When the tests ran they'd fail, because their directory had been
deleted.
By making the custom `copyExamples` and `copyConfiguration` tasks normal
tasks (i.e. not `type: Copy`), …
> bau: Fix issue with ./gradlew clean test

- configuration/local/msa.yml
- docker-run.sh
- run.Dockerfile
Added the necessary script, config and Dockerfile to allow
image to be built for running in docker with local-startup
Authors: @andy-paine
> Firebreak: Add scripts and Dockerfile to run app in container

- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/ConditionsValidator.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/DateTimeComparator.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/EidasAttributeQueryAssertionValidator.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validators/ConditionsValidatorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validators/DateTimeComparatorTest.java
Fix fuzzy time matching so that IssueInstant validation passes despite small discrepancies in server time.
Make the 'clockSkew' an optional value in the app config, with a default value of 30 seconds. (As recommended by Richard)
Fix some of the NotBefore eIDAS validation.
Solo: @hugh-emerson
> BAU: fix time validation

- build.gradle
It contains changes in metadata bindings to make the eIDAS metadata resolver factory thread safe.
> BAU: Use a later version of the SAML libs

- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/factories/EidasAttributeQueryValidatorFactory.java
- src/main/java/uk/gov/ida/matchingserviceadapter/saml/transformers/inbound/transformers/EidasAttributesBasedAttributeQueryDiscriminator.java
The newer version of verify-saml-libs have fixes to give metadata resolver unique names when adding them to the metric.
> BAU: Use later version of hub-saml and verify-saml-libs with fixes

- src/main/java/uk/gov/ida/matchingserviceadapter/factories/EidasAttributeQueryValidatorFactory.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/EidasAttributeQueryAssertionValidator.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/EidasAttributeQueryValidator.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/SamlDigitalSignatureValidator.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validators/EidasAttributeQueryAssertionValidatorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validators/EidasAttributeQueryValidatorTest.java
Uses the new SignatureTrustEngine support from saml-metadata-bindings
for verifying the signatures of eIDAS Assertions.
> firebreak: use new signature validators for eidas assertions

- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
Includes changes to modify Eidas Metadata Resolvers to use a single
client between all resolvers and only update necessary Resolvers upon
refresh.
> EID-584: Update saml-libs to latests version

- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterApplication.java
- src/main/java/uk/gov/ida/matchingserviceadapter/domain/OutboundResponseFromMatchingService.java
- src/main/java/uk/gov/ida/matchingserviceadapter/domain/OutboundResponseFromUnknownUserCreationService.java
- src/main/java/uk/gov/ida/matchingserviceadapter/domain/UserAccountCreationAttribute.java
- src/main/java/uk/gov/ida/matchingserviceadapter/exceptions/SamlOverSoapExceptionMapper.java
- src/main/java/uk/gov/ida/matchingserviceadapter/logging/MdcHelper.java
- src/main/java/uk/gov/ida/matchingserviceadapter/rest/soap/SoapMessageManager.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/AssertionService.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/AttributeQueryService.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
Removed reference to depricated Trowables.propogate(e).
Removed reference to depricated ISO8601DateFormat().
Cleaned up unused imports.
Simplified unnecessary private method call.
Changed to use SingletonList where appropriate.
> BAU: Fixed code analysis warnings.

- src/integration-test/java/uk/gov/ida/integrationtest/UserAccountCreationIntegrationTest.java
- src/main/java/uk/gov/ida/matchingserviceadapter/domain/UserAccountCreationAttribute.java
- src/main/java/uk/gov/ida/matchingserviceadapter/saml/factories/UserAccountCreationAttributeFactory.java
- src/test/java/uk/gov/ida/matchingserviceadapter/saml/transformers/outbound/transformers/AssertionServiceAssertionToAssertionTransformerTest.java
UserAccountCreationAttributeFactory sets the to/fom dates.
We've also added a check in the integration test to verify this.
> EID-694: Make MSA send from/to date in UAC Response Attributes

- configuration/local/msa.yml
Still requires 12-factoring but allows the necessary
options to be configured for running acceptance tests
locally
> BAU: Modify local configuration file for local-startup

- verify-matching-service-test-tool/build.gradle
- Remove usage of deprecated JUnit Platform Gradle Plugin.
- jaxb-api dependency for test tasks.
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>
> VCU-23: Gradle changes for Java 10.

- RELEASE_NOTES.md
SUPPORT FOR COMPILATION ON JAVA 9 AND 10
- The MSA can now be compiled and run on Java 9 and 10.
- This release has still been compiled on Java 8.
- Gradle Build Script changes were made to support the Java versions above.
MULTI-RELEASE JARS
- Compiling on Java 9 or 10 will produce a multi-release jar.
- A multi-release jar is produced by default when compiling with Java 9 or 10.
- In this case all existing code is compiled with the '--release 8' flag.
- This means any jar compiled with Java 9 or 10 can be executed under Java 8, giving users the flexibility to stay on an earlier Java version if required.
> VCU-93: MSA Release Notes for Java 9 and 10 changes.

- RELEASE_NOTES.md
Releases 3.00, 3.01, 3.02 contain changes which have been causing
problems that are documented in the Zen Desk ticket.  Adding a message to
encourage users not to use these releases
Solo: @kgarwood
> ZD59163: Adding notice to deprecate using problematic releases

- src/main/java/uk/gov/ida/matchingserviceadapter/validators/SubjectValidator.java
The German eIDAS Middleware returns NameIDs with the format set to
*transient*. Normally, Verify IDPs return *persistent*. We should allow
the validator to accept both types of NameID since it doesn't really
affect the journey.
> EID-842: Support transient NameID format for middleware

- RELEASE_NOTES.md
- build.gradle
- src/integration-test/java/uk/gov/ida/integrationtest/EidasMatchingIntegrationTest.java
- A change has been made to saml libs to give support to the above signing algorithms. 
- This is to fulfil eidas crypto requriements as laid out in the spec
- Use RSASSA-PSS signing algorithm for eidas integration tests
Co-authored-by: Simon Worthington <simon.worthington@digital.cabinet-office.gov.uk>
> EID-835 - Give the MSA support for the RSASSA-PSS and ECDSA algorithms

- build.gradle
- This is causing conflicts with verify-local-startup as it is trying to use the same debug port twice
> bau - remove local debug option

- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/exceptions/InvalidCertificateException.java
- src/test/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModuleTest.java
Is this a good idea?
Stop trying to convert certificates with the Java equivalent of 'grep -v'.
Instead, fully parse the certificate and then use conversion routines to get
the output format we desire.
In this case, we want the DER representation of the certificate, base64-encoded
closes #96
> 96: Convert PEM certificates to base64-encoded DER properly

- build.gradle
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72448
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72449
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72450
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72451
These vulns were identified by running `snyk test --file=build.gradle`.
(Note that the web interface to Snyk incorrectly resolves our Gradle dependencies, so reports a bunch of other vulnerabilities.)
Still, the command line also reports other libs need updating too (they are just more complicated to upgrade) so I will raise a separate ticket about that.
> Update jackson-databind library to fix High Severity vulnerabilities.

- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/AssertionTimeRestrictionValidator.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/ConditionsValidator.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/SubjectValidator.java
- src/test/java/uk/gov/ida/matchingserviceadapter/controllogic/UnknownUserResponseGeneratorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/saml/factories/UserAccountCreationAttributeFactoryTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionServiceTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/services/UnknownUserResponseGeneratorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validator/AttributeQuerySignatureValidatorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validator/ConditionsValidatorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validator/SubjectValidatorTest.java
- src/test/java/uk/gov/ida/matchingserviceadapter/validator/TimeRestrictionValidatorTest.java
This commit cleans up a few things, such as whitespace and unused
imports.
It's also adds some tests for UserAccountCreationAttributeFatory, and
extends some tests for EidasAssertionServiceTest.
> EID-713 Clean up

- src/integration-test/java/uk/gov/ida/integrationtest/helpers/MatchingServiceAdapterAppRule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterConfiguration.java
The keepAlive value determines how long a persistent connection is kept open on the client side without being used (between two http requests). This value must be set less than the server side idleTimeout (defaults to 30 seconds in Dropwizard server) otherwise the connection can be closed on the server’s end resulting a org.apache.http.NoHttpResponseException when the client tries to reuse the connection.
SAML SOAP Proxy HTTP client, SAML SOAP Proxy MSA client and SAML SOAP Proxy MSA HealthCheck client had keepAlive set to 60 seconds. SAML Engine server's and MSA server's idleTimeout defaulted to 30 seconds. The clients' keepAlive were greater than the servers' idleTimeout. There were 5,422 org.apache.http.NoHttpResponseException in SAML SOAP Proxy log file in production over the last 7 …
> AUTO-340: Fix keepAlive issue

- build.gradle
Builds of `verify-saml-libs` >= `188` are compiled using OpenJDK-11.
`verify-matching-service-adapter` is still compiled for Java 8, which will produce a compiler error like:
`class file has wrong version 55.0, should be 52.0`, when trying to compile in a `verify-saml-libs` dependency >= 188.
This PR uses a build of `verify-saml-libs` with compile target set to `1.8` to avoid this compile error.
The travis build for the project compiles against `oraclejdk8` and `openjdk8`, which will help validate the change.
This PR follow on from https://github.com/alphagov/verify-saml-libs/pull/63
> Use verify-saml-libs compiled using openjdk-11 but with java 8 compile target

- src/main/java/uk/gov/ida/matchingserviceadapter/services/MatchingResponseGenerator.java
- src/test/java/uk/gov/ida/matchingserviceadapter/services/MatchingResponseGeneratorTest.java
The version information returned in a custom http header is now redundant. It has been removed.
> BAU: Remove healthcheck HTTP header

- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
The eIDAS SAML profile allows for assertions to be unsigned. The verify
profile does not. Build 193 of saml-libs will allow unsigned assertions
only from eIDAS countries.
> EID-1504 Allow unsigned eIDAS assertions

- configuration/example-lms-msa.yml
- configuration/local/msa.yml
- configuration/test-rp-msa.yml
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/exceptions/ExceptionExceptionMapper.java
- src/test/java/uk/gov/ida/matchingserviceadapter/exceptions/ExceptionExceptionMapperTest.java
MSA logs don't contain a lot of useful information. It's hard to use them to identify what a problem is.
We should implement error logging changes to the MSA so that the full stacktrace is returned to the Verify Hub when an HTTP 500 error happens in the MSA.
There is some further background in Anshul's [investigation into MSA 500 errors](https://docs.google.com/document/d/10-oAqzKiPXu4nzwD9GL7knABwKxOLNY4oUlo6gC4uRA/edit#).
Original Zendesk ticket:
https://govuk.zendesk.com/agent/tickets/3651026
Rename flag `returnStackTraceInResponse` and set default to `true`
This will ensure that all MSAs will return stack trace to us unless we
explicitly ask them to set the renamed flag to `false` in config.
> N7edPMiO: Improve MSA Logging

- RELEASE_NOTES.md
We're going to do a joint release of the MSA with the `Make Verify work for users` team (eIDAS).
We've made a couple of changes to the MSA which will go out in this release. We need to: 
+ write release notes for our changes
+ check if anything else has been merged since the last release (except for eIDAS's changes) and write notes for that
Added release note for extra logging (https://github.com/alphagov/verify-matching-service-adapter/pull/122)
Added release note for multiple firstname filtering (https://github.com/alphagov/verify-matching-service-adapter/pull/110)
Added release note for filter of multiple attribute values to UAC (https://github.com/alphagov/verify-matching-service-adapter/pull/113)
Added additional notes for other PRs merged since last release 
(excepting eIDAS related …
> rp7KfRqL: Write MSA release notes for changes made by data team in Q1

- .travis.yml
Travis seem to be having issues installing oraclejdk8 on Xenial, which this is currently built on (somehow). There some [chat about it here.](https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038)
See here for an example of the issue: https://travis-ci.org/alphagov/verify-matching-service-adapter/jobs/547723703
See here for an example of oraclejdk8 being installed on Trusty: https://travis-ci.org/alphagov/verify-saml-libs/jobs/547765923
Dropping to Trusty should resolve this.
> BAU Build with Trusty on Travis

- build.gradle
This changes build.gradle file to find trust anchor library correctly without throwing any errors.
Author: @adityapahuja
> BAU: Fix missing trust anchor library

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
There was an issue found with the approach used to handle unsigned
assertions. This reverts that work by reverting the code and pulling in
an updated version of saml-libs that does not include the issue.
> EID-1583 Revert eIDAS unsigned assertions handling

- verify-matching-service-test-tool/publish.gradle
The Jenkins build has started to fail after some changes to the gradle
files. The test-tool publication task is looking in the wrong place for
the dist. This should fix that.
> BAU Update test tools publish.gradle

- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/configuration/EuropeanConfigurationConstants.java
- src/main/java/uk/gov/ida/matchingserviceadapter/configuration/EuropeanConfigurationDefaultsHelper.java
- src/main/java/uk/gov/ida/matchingserviceadapter/configuration/EuropeanIdentityConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/configuration/MatchingServiceAdapterMetadataConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
- src/test/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionServiceTest.java
A quick update to manage `acceptableHubConnectedEntityIds` as a List rather than an array.
See feedback from: https://github.com/alphagov/verify-matching-service-adapter/pull/140
> EID-1683 audience validation: move from arrays to lists

- src/integration-test/java/uk/gov/ida/integrationtest/interfacetests/EidasExampleSchemaTests.java
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/configuration/EuropeanConfigurationDefaultsHelper.java
- src/main/java/uk/gov/ida/matchingserviceadapter/configuration/EuropeanIdentityConfiguration.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
This change:
- ... makes the `hubConnectorEntityId` configuration option nullable.
- ... defers to the first `acceptableHubConnectorEntityId` if the `hubConnectorEntityId` is not provided.
- ... updates the subdomains inside the potential new entity ids themselves.
> EID-1683 make hubConnectorEntityId optional

- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionService.java
- src/test/java/uk/gov/ida/matchingserviceadapter/services/EidasAssertionServiceTest.java
When the Hub evaluates that eidas assertions are unsigned it provides:
- the entire eidas saml response to the MSA
- and an encrypted secret key, 
as attributes. This Hub work is already merged from https://github.com/alphagov/verify-hub/pull/381
the MSA uses its private encryption key to decrypt the encrypted secret key, uses that key to decrypt the assertions within the eidas saml response, and then unmarshalls the response.
The work above is done by `EidasUnsignedMatchingDatasetUnmarshaller`, and is already merged in `saml-libs`, see https://github.com/alphagov/verify-saml-libs/pull/88.
**This PR** allows the MSA to evaluate whether the attributes in the AttributeQuery contains the eidas saml response, and in this case:
- the signature of the assertions is not checked,
- and the …
> Decrypt and unmarshall eidas unsigned assertions in MSA

- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
Construct the`EidasUnsignedMatchingDatasetUnmarshaller` with an `EidasValidatorFactory`.
This factory will validate the eidas saml response.
This PR is a subsequence of https://github.com/alphagov/verify-saml-libs/pull/96
> Use EidasValidatorFactory in EidasUnsignedMatchingDatasetUnmarshaller

- build.gradle
- src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
- src/main/java/uk/gov/ida/matchingserviceadapter/validators/SubjectValidator.java
Part two of a two-part PR to validate the eidas saml response in the MSA.
Part 1 is https://github.com/alphagov/verify-saml-libs/pull/97
This PR supplies the `EidasUnsignedMatchingDatasetUnmarshaller` with a validation lambda, which it will use to validate the eidas assertions after they are decrypted.
The validation is a copy of that at:
`uk.gov.ida.matchingserviceadapter.services.EidasAssertionService#validateCountryAssertion`
except for omitting assertion signature validation.
> EID-1604 Supply a validator to EidasUnsignedMatchingDatasetUnmarshaller

- build.gradle
Version number is required in order to create correctly-named zip.
> EID-1698: fix release process (version number)

- ci/manifest.yml.tmpl
This change replaces a hardcoded value with a variable for METADATA_ENTITY_ID. This will allow us to configure a job to set the variable to a different entity id for different environment.
Author: @adityapahuja
> AUT-14: Make METADATA_ENTITY_ID configurable

- configuration/compatibility-testing/msa-backcompat-manifest.yml.tmpl
- configuration/compatibility-testing/test-rp-msa-3.1.0-840.yml
- configuration/compatibility-testing/test-rp-msa-4.1.0-884.yml
- configuration/compatibility-testing/test-rp-msa-4.2.1-901.yml
This adds config files for use in deploying old supported versions of the MSA for our backward-compatibility tests.
Previously, these files lived unmanaged on the disk of jenkins, in /srv/maven.  They should probably be checked into source control instead.
The config files are all the same, but I'm keeping different files for different versions because:
- it's how the backward-compatibility tests used to work
- it allows us to change the config file format between MSA versions
> Add msa backward compatibility config

- USAGE_README.md
Has a link to "full documentation on how to use the MSA" pointing to http://alphagov.github.io/rp-onboarding-tech-docs/pages/msa/msa.html
This page has a redirect which takes the user to the home page of the Verify tech docs, which isn't particularly useful. The link should point to
https://www.docs.verify.service.gov.uk/legacy/build-ms/msa/#matching-service-adapter
links in matching-service-adapter will be fixed in upcoming PR in www.docs.verify.service
> ZD-4070599: Fixed broken link

- ci/build.yml
The concourse build pipeline uses a semver resource to keep track of
different builds of the MSA. Every new PR that's merged triggers a build
and the pipeline bumps the patch version. This new version is used as
the version number for a draft github release.
When we want to generate a new release of the MSA for use by RP's we
bump the version in the `settings.gradle`. This will almost always
either include a major or minor bump.
This commit allows the build pipeline to pick up that change and update
the Concourse version to match. This will then produce a draft release
on Github with the correct version which we can then promote to a full
release.
See the pipeline config here for context: https://github.com/alphagov/verify-infrastructure-config/blob/master/pipelines/deployer/deploy-stubs.y …
> HUB-539: Keep Concourse MSA version in step with local version

- ci/build.yml
It would appear that if you want to bump the remote version, you need to
update the `version` file, not the `number` file.
> HUB-697: Update correct semver file

- ci/build.yml
If we went to propagate the update version, it needs to be an output.
> BAU: Add msa-version as a task output

- RELEASE_NOTES.md
- settings.gradle
Due to some issues with the new logic to keep the Concourse semver
version in line with the version in settings.gradle we need to bump to a
slightly later version and allow the pipeline to re-run.
> BAU: Bump patch version to re-align versions

- ci/example-lms-msa-manifest.yml
- configuration/compatibility-testing/test-rp-msa-5.0.2.yml
- configuration/example-lms-msa.yml
When the Concourse job actually deploys the test-rp, it looks for this
file based on the git tag associated with the MSA release. In this case
it's 5.0.2.
As part of releasing the VSP we spin up an MSA: https://cd.gds-reliability.engineering/teams/verify/pipelines/verify-service-provider/jobs/deploy-msa-in-integration
This MSA is just pulled from master and uses the config that we're
changing here. That config is still looking for the old trust stores so
we need to remove it. There will also be a change to the pipeline to
stop providing the variables to the manifest.
> HUB-697: Fix up some config

- configuration/example-lms-msa.yml
For some reason we were using an `x509` type for the cert. In 99% of
places we use encoded.
This update hopefully make it more intuitive for future people.
> BAU: Update example-lms-msa.yml to use encoded signing cert

- Dockerfile
- configuration/local/msa.yml
The Dockerfile in the Matching Service adapter is actually broken.  There is no target called install.  For this reason I have updated
the Dockerfile to point to installDist which I think should be the correct gradle target.
> HUB-720 Fix the broken Dockerfile

- RELEASE_NOTES.md
- build.gradle
This version includes a fix for a bug where metadata resolvers were not
picking up on changes to a countries trust-anchor.
> BAU: Upgrade saml-libs to 249

- Dockerfile
This is a small update to update to the Dockerfile to bump the versions of Gradle and JDK we use.
> HUB-708 Update Gradle and JDK in Dockerfile

- configuration/test-rp-msa.yml
Currently the test-rp MSAs across staging/integration/prod have the same
entity ID. This makes onboarding to self-service impossible.
This change will allow then to be namespaced while maintaining backward
compatibility.
> HUB-795: Make test-rp-msa MSA entityId configurable

- ci/manifest.yml.tmpl
This allows the MSA entity ID configured in the pipeline to be passed
through to the PaaS deployment.
> HUB-795: Pass entity ID to PaaS deploy

- configuration/test-rp-msa.yml
This config file is used by the test-rp MSA in staging and integration.
The integration MSA seems to be struggling to validate the new
federation metadata signature, which is signed by a G3 CA.
Removing this config will allow the MSA to use the default trust stores
which contain the CAs necessary.
Interestingly I've manually inspected the trust store the MSA was using
and it looks like it does contain the G3 CAs. Either way, this change
will eliminate a variable and hopefully make diagnosis of the issue
easier.
> HUB-817: Use default trust stores in test-rp msa

- RELEASE_NOTES.md
- settings.gradle
Created as part of the [MSA release process](https://verify-team-manual.cloudapps.digital/documentation/support/msa-release/) after running `./do_release verify_matching_service_adapter`. We agreed that this is minor version bump to `5.1.0`, as there is no change in config required.
> EID-2031 Update RELEASE_NOTES and build.gradle for release 5.1.0

- configuration/compatibility-testing/test-rp-msa-5.1.0.yml
Add MSA version 5.1.0 to backwards compatible testing.
Retain
```
europeanIdentity:
enabled: true
```
as this is a flag to send a universal matching dataset to the local matching service
> EID-2031 Add MSA release 5.1.0 to backwards compatibility testing

- RELEASE_NOTES.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Bintray and jcentre are going away. This updates the public builds to
pull from maven central instead. It also bumps the versions of our
libraries to ensure they're coming from maven central.
It also removes the ben maines plugin which was sold old it didn't work
anymore.
> HUB-912: Pull from maven central

- Dockerfile
The build breaks under Gradle 7 so for the time being we have pinned the Gradle version to 6.9.0 and it now pulls from DockerHub as our other repos should now do.
> BAU Pin gradle version to 6.9.0

- .travis.yml
- RELEASE_NOTES.md
- build.gradle
- verify-matching-service-test-tool/build.gradle
Update logback to 1.2.9 to mitigate CVE-2021-42550
See the article "16th of December, 2021, Release of version 1.2.9" at http://logback.qos.ch/news.html
> BAU Update logback

- RELEASE_NOTES.md
- settings.gradle
Bump MSA from version 5.1.0 to 5.2.0.
The version number bump will start the MSA release pipeline
> BAU Update RELEASE_NOTES and build.gradle for release 5.2.0

- RELEASE_NOTES.md
- build.gradle
One of the quirks of DropWizard 2 was having to import this lib so that
we can return XML media types.
This allows the MSA to serve it's metadata for consumption by RPs.
> BAU: Import jersey-media-jaxb

- RELEASE_NOTES.md
- settings.gradle
This adds no functional changes. It's being bumped to align version in
the pipeline.
The Concourse pipeline maintains it's own MSA version semver resource
which is used when publishing releases to GitHub. The pipeline bumps the
patch version of this semver resource every time a change is merged.
This means that if you want to release a patch version to GitHub it's
very difficult - the patch number on the semver resource will already be
a few versions ahead of the version defined in `settings.gradle`.
We should decouple the GitHub release version from Concourse's internal
semver resources, but for now this should bring the two into alignment
to get the release out.
> BAU: Update version 5.2.3
