build.gradle
=> bau: library upgrades

USAGE_README.md
Fixed link to external onboarding guide
=> BAU: Fix broken link

build.gradle, src/integration-test/java/uk/gov/ida/integrationtest/MatchingServiceAdapterAppRuleTest.java, src/integration-test/java/uk/gov/ida/integrationtest/UserAccountCreationAppRuleTest.java, src/integration-test/java/uk/gov/ida/integrationtest/helpers/AssertionHelper.java, src/main/java/uk/gov/ida/matchingserviceadapter/mappers/DocumentToInboundMatchingServiceRequestMapper.java, src/main/java/uk/gov/ida/matchingserviceadapter/saml/transformers/inbound/decorators/SamlAttributeQueryAssertionsValidator.java, src/main/java/uk/gov/ida/matchingserviceadapter/validators/StringValidators.java, src/test/java/uk/gov/ida/matchingserviceadapter/builders/InboundMatchingServiceRequestBuilder.java, src/test/java/uk/gov/ida/matchingserviceadapter/controllogic/UnknownUserAttributeQueryHandlerTest.java, src/test/java/uk/gov/ida/matchingserviceadapter/domain/UserAccountCreationAttributeExtractorTest.java, src/test/java/uk/gov/ida/matchingserviceadapter/saml/transformers/outbound/transformers/MatchingServiceAssertionToAssertionTransformerTest.java, src/test/java/uk/gov/ida/matchingserviceadapter/validators/AttributeValidatorTest.java, src/test/java/uk/gov/ida/matchingserviceadapter/validators/StringValidatorsTest.java, src/test/java/uk/gov/ida/matchingserviceadapter/validators/SubjectConfirmationDataValidatorTest.java
=> TT-1419 Validate idp assertion consistency

verify-matching-service-test-tool/README.md
=> TT-1758 update README with test tools cli instructions

verify-matching-service-test-tool/publish.gradle
=> BAU: Adding task to publish test tool zip to artifactory

publish.gradle
=> TT-1846 : Adds task to publish MSA zip to artifactory

build.gradle, publish.gradle, settings.gradle, verify-matching-service-test-tool/build.gradle
upload MSA zip to artifactory.
Authors: @SKeerthana
=> TT-1846 : Adding version number to settings.gradle and using it when we

build.gradle, src/test/java/uk/gov/ida/matchingserviceadapter/exceptions/ExceptionExceptionMapperTest.java, src/test/java/uk/gov/ida/matchingserviceadapter/exceptions/SamlOverSoapExceptionMapperTest.java
* bump dropwizard-saml version
* add a JerseyGuiceUtils.reset() for building in docker on the official openjdk images
Pair: WillPa
=> bau: misc fixes

src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
We need to ensure that the MSA is able to resolve the trust anchor and
in turn that each of the `MetadataResolver`s it provides is validating
the metadata they read.
The `EidasTrustAnchorHealthCheck` from saml-metadata-bindings should
fulfil both of these requirements.
Author: @vixus0
=> EID-419: Add trust anchor healthcheck

build.gradle, src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
Client is now shared for TrustAnchorResolver and MetadataResolver.
Solo: @minhngocd
=> BAU: update libs for the MSA.

build.gradle
Updates libraries: ida-test-utils, hub-saml
=> BAU: Update libs to the latest versions

prod-config.yml, test-config.yml
We need to provide some guidance around config files. Full context
is in tech docs but this provides some light suggestions about
configuring for eidas/without eidas
=> EID-634: Add european identity section to example config files

RELEASE_NOTES.md
=> EID-634: Fix link in the detail release note

build.gradle, verify-matching-service-test-tool/build.gradle
Gradle build script changes to support multi-release jars.
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>
=> VCU-87: MSA Multi Release Jar

RELEASE_NOTES.md
This is in preparation for the MSA release.
=> EID-774 : Updated release note with the validation fixes.

src/integration-test/java/uk/gov/ida/integrationtest/MetadataRefreshTaskIntegrationTest.java, src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterApplication.java, src/main/java/uk/gov/ida/matchingserviceadapter/MatchingServiceAdapterModule.java
=> bau: add metadata refresh tasks + tests

RELEASE_NOTES.md, build.gradle
https://trello.com/c/2HRytw7O/412-upgrade-msa-to-dropwizard-135
=> Upgrade to dropwizard 1.3.5 (jetty security fixes).

.travis.yml, build.gradle
Added github authentication so we don't fall foul of the API rate limiting
=> BAU: report coverage to Codacy

RELEASE_NOTES.md, settings.gradle
=> Update RELEASE_NOTES and build.gradle for release 4.0.0

.travis.yml
=> BAU: Fix Travis

RELEASE_NOTES.md, settings.gradle
=> Update RELEASE_NOTES and build.gradle for release 4.1.0

RELEASE_NOTES.md, settings.gradle
As prepared by `do_release verify_matching_service_adapter` ...
=> Update RELEASE_NOTES and build.gradle for release 4.2.0

.travis.yml, ci/manifest.yml.tmpl
This change adds Logit service to manifest.yml file so that MSA can start sending log messages to Logit.
Author: @adityapahuja
=> AUT-14: Start sending log messages to Logit

build.gradle, verify-matching-service-test-tool/build.gradle
- We are replacing whitelist-repos with allowed-repos. We are running both for now so we can switch it over.
**To Review**
Check that the URL for the allowed-repos can be accessed.
=> EXErxpzy - Replace whitelist with allowlist

RELEASE_NOTES.md, settings.gradle
=> Update RELEASE_NOTES and build.gradle for release 5.0.0

Dockerfile
Update the Dockerfile to use GitHub Container Registry
=> HUB-774 Update the Dockerfile to use GHCR

RELEASE_NOTES.md, doc/release-details/5.1.0.md
Add release notes for the removal of eIDAS support.
The release notes markdown links to a more detailed release details page.
=> EID-2085 Add 5.1.0 release notes

.github/dependabot.yml, build.gradle
- Remove unused dependencies
- Update existing dependencies
- Add dependabot to the project
=> BAU - Upgrade dependencies and add dependabot

build.gradle
Co-authored-by: Paul Hennessey <paul.hennessey@digital.cabinet-office.gov.uk>
=> add constraint on opensaml to pull in bcprov-jdk15on:1.67
